baseURL = "https://syn-server.ru"
defaultContentLanguage = "ru"
title = "Syn's Blog"
enableInlineShortcodes = true

[params]
  description = "Блог Каснова Никиты"
  copyright = "© 2020 Краснов Никита"

[menu]
  [[menu.main]]
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"

# Read more about [markup.goldmark.renderer]
# https://github.com/yuin/goldmark/#html-renderer-options
# https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup.goldmark.renderer]
  unsafe = true
