baseURL = "https://syn-server.ru"
defaultContentLanguage = "ru"
title = "Syn's Blog"

[params]
  description = "Блог Каснова Никиты"
  copyright = "© 2020 Краснов Никита"
  mainSections = ["posts"]

[menu]
  [[menu.main]]
    name = "записи"
    title = "записи"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    name = "про меня"
    title = "про меня"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:section/:filename/"
